#!/bin/bash
# Creates a shared app user and per-app databases from environment variables.
# Mounted as /docker-entrypoint-initdb.d/init-databases.sh in the postgres container.
set -euo pipefail

# --- Shared app user ---
APP_USER="${APP_DB_USER:-masuite_app}"
APP_PASSWORD="${APP_DB_PASSWORD:-}"

if [ -n "$APP_PASSWORD" ]; then
    echo "Creating shared app user '$APP_USER'..."
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_USER}') THEN
                CREATE ROLE "${APP_USER}" WITH LOGIN PASSWORD '${APP_PASSWORD}';
            END IF;
        END
        \$\$;
        -- Allow app user to create C-language functions (needed by Docs/Impress)
        ALTER ROLE "${APP_USER}" SUPERUSER;
EOSQL
fi

# --- Per-app databases ---
# APP_DB_NAMES is a space-separated list of database names (e.g. "docs_db meet_db drive_db").
# Generated by the setup wizard. All databases are owned by the shared app user.
for db_name in ${APP_DB_NAMES:-}; do
    if [ -n "$APP_PASSWORD" ]; then
        echo "Creating database '$db_name' owned by '$APP_USER'..."
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            SELECT 'CREATE DATABASE "${db_name}" OWNER "${APP_USER}"'
            WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${db_name}')\gexec
            GRANT ALL PRIVILEGES ON DATABASE "${db_name}" TO "${APP_USER}";
EOSQL

        # Install common extensions needed by La Suite apps
        echo "Installing extensions in '$db_name'..."
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${db_name}" <<-EOSQL
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE EXTENSION IF NOT EXISTS unaccent;
            GRANT ALL ON SCHEMA public TO "${APP_USER}";
            ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "${APP_USER}";
            ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "${APP_USER}";
            ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "${APP_USER}";
EOSQL
    fi
done

# --- Keycloak (separate user) ---
KC_DB_NAME="${KEYCLOAK_DB_NAME:-keycloak_db}"
KC_DB_USER="${KEYCLOAK_DB_USER:-keycloak_user}"
KC_DB_PASSWORD="${KEYCLOAK_DB_PASSWORD:-}"

if [ -n "$KC_DB_PASSWORD" ]; then
    echo "Creating Keycloak database '$KC_DB_NAME' with user '$KC_DB_USER'..."
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${KC_DB_USER}') THEN
                CREATE ROLE "${KC_DB_USER}" WITH LOGIN PASSWORD '${KC_DB_PASSWORD}';
            END IF;
        END
        \$\$;
        SELECT 'CREATE DATABASE "${KC_DB_NAME}" OWNER "${KC_DB_USER}"'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${KC_DB_NAME}')\gexec
        GRANT ALL PRIVILEGES ON DATABASE "${KC_DB_NAME}" TO "${KC_DB_USER}";
EOSQL
fi

echo "Database initialization complete."
